package vadimsuraev.PACK.ProxyLib.ProxyLibTypes;

public enum PackEnvelopeKinds
{
    PACK_ENVELOPE_DUMMY_KIND,
    PACK_ENVELOPE_UPSTREAM_MSG_KIND,
    PACK_ENVELOPE_UPSTREAM_DATA_KIND,
    PACK_ENVELOPE_DOWNSTREAM_MSG_KIND,
    PACK_ENVELOPE_DOWNSTREAM_DATA_KIND
}